//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proje1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kayıt
    {
        public string KullaniciAdi { get; set; }
        public string Şifre { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public Nullable<decimal> Telefon { get; set; }
    }
}
